services:

  frontend:
    container_name: games-frontend
    build: frontend
    ports:
      - "20080:80"
    volumes:
      - composer-cache:/root/.composer/cache:delegated
      - ./:/app
      - cron-spool:/var/spool/cron/crontabs
    depends_on:
      mysql:
        condition: service_healthy
    environment:
      DB_HOST: mysql
      DB_NAME: yii2advanced
      DB_USER: yii2advanced
      DB_PASSWORD: secret

  backend:
    container_name: games-backend
    build: backend
    ports:
      - "21080:80"
    volumes:
      - composer-cache:/root/.composer/cache:delegated
      - ./:/app
    depends_on:
      mysql:
        condition: service_healthy
    environment:
      DB_HOST: mysql
      DB_NAME: yii2advanced
      DB_USER: yii2advanced
      DB_PASSWORD: secret

  mysql:
    container_name: games-mysql
    image: mysql:8.0
    ports:
      - "23306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: verysecret
      MYSQL_DATABASE: yii2advanced
      MYSQL_USER: yii2advanced
      MYSQL_PASSWORD: secret
    volumes:
      - mysql-data:/var/lib/mysql
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost", "-uroot", "-pverysecret" ]
      interval: 5s
      timeout: 5s
      retries: 10

volumes:
  composer-cache:
  mysql-data:
  cron-spool:
